app = 'topheroes-bot'
primary_region = 'sin'

[build]

[env]
  NODE_ENV = 'production'

[mounts]
  source = 'bot_data'
  destination = '/data'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
